# Generated by Django 6.0.2 on 2026-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="image",
            field=models.ImageField(default="test", upload_to="images"),
            preserve_default=False,
        ),
    ]
