# Generated by Django 6.0.2 on 2026-09-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetup", "0004_participant_meetup_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2021-04-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="test@test.com", max_length=254),
            preserve_default=False,
        ),
    ]
